### ISSUE TITLE
Urgent! Base packages need to have the highest popularity

### ISSUE THREAD

**Issue by ddmkr** [datacamp/rdocumentation-app#17]
When searching, functions for base packages (`mean`, `hist`, `rnorm`, etc) Should be shown before all other results.

**Comment by ddmkr** [comment]
@ludov04 I would give this issue highest priority.

**Comment by ludov04** [comment]
Mmmh, I can see the problem, base packages is not in on rstudio-logs so download count is 0

**Comment by ddmkr** [comment]
I would give those an extremely high priority.

**Comment by ludov04** [comment]
Ok so one solution can be to add a json field `part_of_r` in elasticsearch, that I would set to true for thoses packages:
```
base
datasets
graphics
grDevices
grid
methods
parallel
splines
stats
stats4
tcltk
tools
translations
utils
``` 
and that would boost the popularity in order to be on top of everything else

**Comment by ddmkr** [comment]
Seems like a good solution. How long would this take to implement?

**Comment by ludov04** [comment]
About 1 or 2 hour, the uncertainty is on how exactly it is easy to use a boolean field to boost popularity, and how to make sure that will be on top of package with huge number of download
