### ISSUE TITLE
Increase 404 pages rdocumentation

### ISSUE THREAD

**Issue by martijnsublime** [datacamp/rdocumentation-app#24]
Increase 404 pages rdocumentation:
https://www.dropbox.com/s/y0k7kdpihw6fz17/Screenshot%202016-06-30%2009.25.32.png?dl=0

**Comment by ddmkr** [comment]
@ludov giving you access to Google Webmaster for RDocs.

**Comment by ludov04** [comment]
I generated sitemap files and submitted it to google crawler, should be back to normal when google has processed it
