### ISSUE TITLE
Percentile calculation

### ISSUE THREAD

**Issue by jjf234** [datacamp/RDocumentation-app#261]
Hi, I'm curious to know if the percentile on each page is as expected.  For example, I randomly picked two packages and it seems like the one with the lower monthly downloads has the higher percentile:
- 1,087 Monthly downloads >  84th Percentile (http://www.rdocumentation.org/packages/mcmc/versions/0.9-4)
- 1,253 Monthly downloads > 67th Percentile (http://www.rdocumentation.org/packages/MCMCglmm/versions/2.22.1)

Any insight would be appreciated. Thanks.

**Comment by ludov04** [comment]
Hi, 

Percentile are calculated over total downloads, displayed downloads are direct downloads.
In your example, mcmc has 4,158 total downloads while MCMCglmm has 2144 total downloads.

You can see the number of total downloads by hovering the 'i' icon.

I agree it's not very clear, we'll try to improve that, thanks for the feedback.
