### ISSUE TITLE
Can't log in inside RStudio pane

### ISSUE THREAD

**Issue by filipsch** [datacamp/RDocumentation-app#273]
To reproduce:

- start RStudio
- load `RDocumentation`: `library(RDocumentation)`
- Type `?mean`.
- In the RDocumentation view that appears, click "Sign in" top right.
- Pass credentials for an account you already made.
- Clicking "Login" doesn't do anything...

@ludov04 Am I missing something here?

**Comment by ludov04** [comment]
Apparently, it actually logs you in but fails to redirect you for some reasons
