### ISSUE TITLE
Package version not updated for mclust

### ISSUE THREAD

**Issue by luca-scr** [datacamp/RDocumentation-app#279]
Hi,

I just realised that for package mclust the referenced version in RDocumentation is the 5.0.2 whereas the version on CRAN is the 5.2 since 2016-03-31.
Is this a bug?

Thanks.

Luca

**Comment by ludov04** [comment]
Hi, 

It seems that the 5.2 version is there https://www.rdocumentation.org/packages/mclust/versions/5.2, but when searching for mclust, the 5.0.2 version appears. 
This is indeed a bug.

We'll look into that, thanks for raising it.

Ludovic

**Comment by kingaa** [comment]
Not sure if this is the same or a different bug, but RDocumentation has by default version 1.4.1.1 of package **pomp**, but we are up to version 1.10 now on CRAN.

**Comment by luca-scr** [comment]
I just checked and now is solved. Thanks.
