### ISSUE TITLE
Bad rendering on R6::R6Class() page

### ISSUE THREAD

**Issue by richierocks** [datacamp/RDocumentation-app#281]
In the details section.

https://www.rdocumentation.org/packages/R6/versions/2.2.0/topics/R6Class

![screenshot 2016-12-23 11 20 05](https://cloud.githubusercontent.com/assets/197589/21458101/db4c571e-c901-11e6-9cdb-9b6187533689.png)

**Comment by ludov04** [comment]
Related to #289
