### ISSUE TITLE
Workspace should be shared between code blocks in community examples

### ISSUE THREAD

**Issue by richierocks** [datacamp/RDocumentation-app#283]
I tried creating a community example for the `browser()` function.

https://www.rdocumentation.org/packages/base/topics/browser

The example uses several code blocks, but the workspace begins empty for each of them.  This means that when you run the second code block, it fails because it forgot about the function that was defined in the first block.

This severely limits the type of examples that you can provide.

**Comment by ludov04** [comment]
Unfortunately, I'm not sure it's possible using the current version of DataCamp Light.
As far as I know, each block use a different session on the multiplexer and so a different docker container.
