### ISSUE TITLE
err msg typo: "The function is not used is your example"

### ISSUE THREAD

**Issue by richierocks** [datacamp/RDocumentation-app#286]
See here:

https://github.com/datacamp/RDocumentation-app/blob/b071e1f187ab0ef208748da0802181bd955ae2da/assets/js/pages/examples.js#L104

Should be 

> The function is not used in your example

Ideally it would also include the name of the function + the aliases for the help page so the user knows what values they should be including.

**Comment by ludov04** [comment]
Should be easy to fix, thanks for reporting

**Comment by ludov04** [comment]
fixed now!
