### ISSUE TITLE
Incorrect redirection of functions with names differing only in case

### ISSUE THREAD

**Issue by richierocks** [datacamp/RDocumentation-app#287]
`base::c` and `base::C` should have separate help pages, as should `graphics::axis` and `graphics::Axis`.

However 

https://www.rdocumentation.org/packages/base/topics/C

points to `?c` and

https://www.rdocumentation.org/packages/graphics/topics/axis

points to `?Axis`.

**Comment by ludov04** [comment]
Seems like they don't even coexist in RDoc. 
Something probably goes wrong between the parsing and the insertion in the database that causes one topic to override the other.

**Comment by ludov04** [comment]
Mysql by default is case insensitive, so RDoc thought it was the same topics, I updated the collation of the table.
However, packages needs to be reparsed to retrigger insertions of topics, I did it for `graphics` and `base`. 
So it is fixed for `Axis`, see
https://www.rdocumentation.org/packages/graphics/topics/axis
https://www.rdocumentation.org/packages/graphics/topics/Axis
For `base::c` however, seems like `c` is in `base` and `C` is in `stats`, so it shouldn't be a problem, see
https://www.rdocumentation.org/packages/stats/versions/3.3.2/topics/C
https://www.rdocumentation.org/packages/base/versions/3.3.2/topics/c
