### ISSUE TITLE
Incorrect escaping of quotes when editing community examples

### ISSUE THREAD

**Issue by richierocks** [datacamp/RDocumentation-app#288]
I added an example to [`read.table()`](https://www.rdocumentation.org/packages/utils/topics/read.table).

The example demonstrated the use of the `quote` argument.  That is, it contained a code snippet with `quote = '"'` inside it.

When I submitted it, it was fine, but when I edited the example again, all the code after the `'"'` had disappeared.

**Comment by ludov04** [comment]
DCL was causing the problem apparently, should be fixed
