### ISSUE TITLE
Rd parsing is buggy in some packages (High priority)

### ISSUE THREAD

**Issue by ludov04** [datacamp/RDocumentation-app#289]
The parsing of the Rd files seems to be funky in somes cases, resulting in bad rendering when showing the doc in html.

It appears that it is often the case in the `Details` section, when it contains `code` blocks

**Comment by ludov04** [comment]
See how we can use https://github.com/hadley/pkgdown from hadley
(It's the new version of staticdocs, that we use now)

**Comment by filipsch** [comment]
In addition, fix malformed URLs. cc @martijnsublime @dwaynemartin
