### ISSUE TITLE
Higher-contrast text please

### ISSUE THREAD

**Issue by kwstat** [datacamp/RDocumentation-app#292]
The RDocumentation website uses very low contrast between text and background.  For example, on this page:
https://www.rdocumentation.org/packages/dplyr/versions/0.5.0?
The background is white, the function names are light blue and the descriptions are light gray. The text is very thin/lightweight.  For some users/display devices, this can be very difficult to read.

Would it be possible to update the theme to improve accessibility for users?

Incidentally, when Revolution was acquired by Microsoft, the Revolution web pages were changed to higher-contrast to meet Microsoft's accessibility guidelines.  Here is an example that shows how the text is much more readable with higher contrast between text and background, and thicker text:
https://mran.microsoft.com/

**Comment by ludov04** [comment]
Indeed, can be a problem for some users, thanks for reporting this.
Also related to this issue https://github.com/datacamp/RDocumentation/issues/59
We'll how we can improve that

**Comment by ludov04** [comment]
The font-size and font-weight are now bigger, should be easier to read

**Comment by kwstat** [comment]
Thanks. Is the change immediately effective or does it need to be released?  Here's what I'm seeing on Rdocumentation (still rather difficult to read) and MRAN today.

![rdocumentation](https://cloud.githubusercontent.com/assets/484260/22946443/0c52f84c-f2bd-11e6-81fe-c03b86d8efce.png)
![mran](https://cloud.githubusercontent.com/assets/484260/22946453/121c95f8-f2bd-11e6-9773-0f2c07a59567.png)
