### ISSUE TITLE
Parsing issue

### ISSUE THREAD

**Issue by flying-sheep** [datacamp/RDocumentation-app#295]
i could puzzle something together from the API, but i’d just like to run a script on my source package which then does it all.

how did you fill the website? is there a crawler?

**Comment by flying-sheep** [comment]
thanks! yes, my package destiny (huh? by “undefined”?) has only its [old 1.x version](https://www.rdocumentation.org/packages/destiny/versions/1.2.1) on there instead of the already released [2.x](http://bioconductor.org/packages/release/bioc/html/destiny.html)

**Comment by filipsch** [comment]
@flying-sheep okay good to know! We're planning to revise the package parsing logic and can use your package as one of the use-cases. I'll keep you posted.

**Comment by filipsch** [comment]
@ludov04 when the new parser is up, could you manually add this package to the work queue to see if it fixes it?

**Comment by ludov04** [comment]
@flying-sheep The new version of your package is on RDocumentation with the correct author and collaborators

**Comment by flying-sheep** [comment]
great, thank you!
