### ISSUE TITLE
Update title tags

### ISSUE THREAD

**Issue by filipsch** [datacamp/RDocumentation-app#297]
- [x] Change title tag of homepage to `R Documentation and manuals | R Documentation`
- [x] Change title tag of package pages to `<package-name> package | R Documentation`
- [x] Change title tag for function pages to `<function-name> function | R Documentation`
- [x] Change title tag for collaborator pages to `<collab-name> | Collaborator | R Documentation`

cc @dwaynemartin @martijnsublime

**Comment by martijnsublime** [comment]
Title tag says "RDocumentation" instead of "R Documentation" https://www.dropbox.com/s/wbxafadxskdjsqj/Screenshot%202017-02-15%2020.03.45.png?dl=0

**Comment by ludov04** [comment]
Ah yeah, I overlooked that, should be fixed now
