### ISSUE TITLE
Missing topics and wrong links

### ISSUE THREAD

**Issue by filipsch** [datacamp/RDocumentation-app#314]
@flying-sheep commented on [Wed Feb 22 2017](https://github.com/datacamp/RDocumentation/issues/70)

My [destiny](https://www.rdocumentation.org/packages/destiny/versions/2.0.3) package contains two main classes, which share a help topic with their creating function:

* DPT/DPT-class
* DiffusionMap/DiffusionMap class

but those topics aren’t available in the index and don’t seem to be on the site at all.

clicking a link that should lead to them leads to some random other package: https://www.rdocumentation.org/link/DPT?package=destiny&version=2.0.3

---

@filipsch commented on [Wed Feb 22 2017](https://github.com/datacamp/RDocumentation/issues/70#issuecomment-281678371)

Moving this bug to RDocumentation-app

**Comment by filipsch** [comment]
@ludov04 Hopefully reposting the job for this package on the SQS queue can solve it?

**Comment by ludov04** [comment]
Hey @flying-sheep

The latest version of your package has been reparsed, the missing topics are now correctly indexed.

https://www.rdocumentation.org/link/DPT?package=destiny&version=2.0.4
https://www.rdocumentation.org/link/DiffusionMap?package=destiny&version=2.0.4

**Comment by flying-sheep** [comment]
great, thank you!
