### ISSUE TITLE
www.rdocumentation.org stuck at Feb 22

### ISSUE THREAD

**Issue by AndreMikulec** [datacamp/RDocumentation-app#321]
https://www.rdocumentation.org/trends

is stuck at Feb 22

```
Newest packages 
RcppBlaze	Wed Feb 22 2017 14:13:09
```

Did something change?

**Comment by ludov04** [comment]
Thanks for reporting, something seems broken on our end, we'll look into it ASAP

**Comment by ludov04** [comment]
The crawler has been restarted, new packages should be indexed gradually
