### ISSUE TITLE
Show the "Format" field

### ISSUE THREAD

**Issue by franknarf1** [datacamp/RDocumentation-app#326]
[`?nasaweather::atmos`](https://www.rdocumentation.org/packages/nasaweather/versions/0.1/topics/atmos) is missing the most important information, [in the Format field](https://cran.r-project.org/web/packages/nasaweather/nasaweather.pdf). This was an issue in the first chapter of the R Markdown course which suggests looking at `?atmos` through the web interface that uses RDocumentation.

Not sure if this is the right place to put this. The two websites (Datacamp and RDocumentation) have no links for contact or feedback.

**Comment by ludov04** [comment]
Thanks for reporting @franknarf1, you are indeed in the right place for this.
The `Format` section should indeed be part of this page, as you mentioned, we'll look into it

**Comment by ludov04** [comment]
The `Format` section is now part of the documentation:
https://www.rdocumentation.org/packages/nasaweather/versions/0.1/topics/atmos
