### ISSUE TITLE
Missing paragraph breaks in some docs

### ISSUE THREAD

**Issue by franknarf1** [datacamp/RDocumentation-app#334]
For [`data.table::fread`](https://www.rdocumentation.org/packages/data.table/versions/1.10.4/topics/fread), the Description and Details sections have multiple paragraphs, but they're combined into one on the site. I see this doesn't happen for some other docs on the site, though.

**Comment by ludov04** [comment]
Thanks for reporting, 
This page was indeed parsed with another version of our parser which didn't support well break lines. 
This has been reparsed with the new version of our parser.
The paragraphs now appear correctly on the page (https://www.rdocumentation.org/packages/data.table/versions/1.10.4/topics/fread)
