### ISSUE TITLE
Support images in docs

### ISSUE THREAD

**Issue by richierocks** [datacamp/RDocumentation-app#335]
[`?points`](https://www.rdocumentation.org/packages/graphics/topics/points) should contain an image in the Details section.

![screenshot 2017-05-01 18 13 09](https://cloud.githubusercontent.com/assets/197589/25596938/e3b83438-2e99-11e7-9dc7-bf5111e819e4.png)

**Comment by ludov04** [comment]
graphics has been reparsed and `[?points](https://www.rdocumentation.org/packages/graphics/topics/points)` should now display images.
New packages that are parsed from now on will support images, old packages will not have image until we implement #294
