### ISSUE TITLE
Improve styling of usage box

### ISSUE THREAD

**Issue by filipsch** [datacamp/RDocumentation-app#337]
@machow commented on [Mon May 15 2017](https://github.com/datacamp/RDocumentation/issues/73)

I was looking at `?rotations` in the GPArotation library. Although the usage section is many lines, it appears to be rendered as a single line in Rdocumentation:

![image](https://cloud.githubusercontent.com/assets/2574498/26063966/8f9a7c2a-395d-11e7-83eb-50d445daa478.png)

see here:

https://www.rdocumentation.org/packages/GPArotation/versions/2014.11-1/topics/rotations

---

@ludov04 commented on [Tue May 16 2017](https://github.com/datacamp/RDocumentation/issues/73#issuecomment-301796559)

Resubmitted it to the new parser, it's better but still not nice.
Tables especially looks very bad (actually it's not displayed as a table)
Concurrent site looks better than us https://rdrr.io/cran/GPArotation/man/rotations.html

**Comment by ludov04** [comment]
Fixed with new parser, table now looks good
