### ISSUE TITLE
Very old packages shown

### ISSUE THREAD

**Issue by robjhyndman** [datacamp/RDocumentation-app#343]
For some reason, v7.3 of the forecast package documentation is shown. V8.0 was released on 23 February. Something is wrong with your updating mechanism.

**Comment by ramnathv** [comment]
@robjhyndman Thanks for letting us know. We will figure out the issue and update the pages so they reflect the latest versions of the packages. cc @ludov04

**Comment by cjyetman** [comment]
Possibly related issue... if you go to https://www.rdocumentation.org/packages/networkD3 it will default to v0.4, the most recent version, but if you use the search bar it always directs you to the page for v0.2.13. Likewise, the [RDocumentation badge](https://www.rdocumentation.org/badges/version/networkD3) shows v0.2.13

**Comment by ludov04** [comment]
The 2 packages mentioned are now up to date and correctly indexed.
Thanks for reporting
