### ISSUE TITLE
Missing tabular data

### ISSUE THREAD

**Issue by richierocks** [datacamp/RDocumentation-app#346]
The Value section of `?Gest` is missing the part describing the columns of the data frame.

https://www.rdocumentation.org/packages/spatstat/versions/1.49-0/topics/Gest

RDoc version:

![screenshot 2017-06-09 17 30 24](https://user-images.githubusercontent.com/197589/26995219-5da26e90-4d39-11e7-92c7-1da3ed14306b.png)

Local RStudio version:

![screenshot 2017-06-09 17 30 50](https://user-images.githubusercontent.com/197589/26995223-6a0e7bec-4d39-11e7-9429-9b251c7da64a.png)

Not sure if this is related, but the documentation is also out of date. The current version of the package is `1.51-0`, but I couldn't find documentation for that version of the function.

**Comment by ludov04** [comment]
This is fixed and new version is there
https://www.rdocumentation.org/packages/spatstat/versions/1.51-0
