### ISSUE TITLE
Argument fields cut off / [object Object] instead of actual value

### ISSUE THREAD

**Issue by jthurner** [datacamp/RDocumentation-app#349]
The doc for [hydroPSO](https://www.rdocumentation.org/packages/hydroPSO/versions/0.3-4/topics/hydroPSO) has a couple of problems:

- Text cut off in Arguments decriptions, compare "par" and "fn" with [source](https://github.com/hzambran/hydroPSO/blob/master/man/hydroPSO.Rd#L26).
For both parameters, the text cuts off around 255 chars (html), but that might as well be coincidence
- In the [Details section](https://github.com/hzambran/hydroPSO/blob/master/man/hydroPSO.Rd#L79), items display as [Object object]
- The Value listing seems to miss a space between parameter & description.

Everything looks fine in RStudio. I'm adding this as a single issue as the docs might just require reparsing.

**Comment by ludov04** [comment]
Thanks for raising this issue, the package has been reparsed, it looks better now
