### ISSUE TITLE
Aesthetics section of ggplot2::geom_*() not displaying

### ISSUE THREAD

**Issue by richierocks** [datacamp/RDocumentation-app#350]
For example, see [`?geom_bar`](https://www.rdocumentation.org/packages/ggplot2/versions/2.2.1/topics/geom_bar)

It should look like this.

![screenshot 2017-06-22 17 48 02](https://user-images.githubusercontent.com/197589/27457497-f89a94f2-5772-11e7-9f40-fb2ac52d4f79.png)

I see this.

![screenshot 2017-06-22 17 48 36](https://user-images.githubusercontent.com/197589/27457512-08143186-5773-11e7-8be4-32a32b70a706.png)

The same problem occurs with other similar pages like `?geom_point`.

**Comment by ludov04** [comment]
Fixed
