### ISSUE TITLE
gstat::krige() missing latest version

### ISSUE THREAD

**Issue by richierocks** [datacamp/RDocumentation-app#354]
The previous version of the page is there.

https://www.rdocumentation.org/packages/gstat/versions/1.1-3/topics/krige

For the current version of the package, there is no page.

https://www.rdocumentation.org/packages/gstat/versions/1.1-4/topics/krige

**Comment by ludov04** [comment]
Newest version is there: https://www.rdocumentation.org/packages/gstat/versions/1.1-5
