### ISSUE TITLE
read_xml/read_html not in rdocumentation?

### ISSUE THREAD

**Issue by richierocks** [datacamp/RDocumentation-app#363]
@Ironholds commented on [Sun Jul 02 2017](https://github.com/datacamp/courses-working-with-web-data-in-r/issues/16)

https://www.rdocumentation.org/packages/xml2/versions/1.1.1 - I can't find either listed. @richierocks any ideas?

**Comment by richierocks** [comment]
The version from 1.0.0 is there, but not 1.1.1.

https://www.rdocumentation.org/packages/xml2/topics/read_xml

**Comment by ludov04** [comment]
This is fixed ! Thanks for raising !
