### ISSUE TITLE
tm pkg out of date

### ISSUE THREAD

**Issue by richierocks** [datacamp/RDocumentation-app#366]
The current version of the `tm` package  on CRAN is `0.7-1`.

The most recent version on RDocs is `0.6-2`.

https://www.rdocumentation.org/packages/tm

**Comment by ludov04** [comment]
Should be fixed now ! 
https://www.rdocumentation.org/packages/tm goes to 
https://www.rdocumentation.org/packages/tm/versions/0.7-1
