### ISSUE TITLE
Collaborator has wrong name on rdocumentation.org

### ISSUE THREAD

**Issue by filipsch** [datacamp/RDocumentation-app#376]
@sabrinamoin commented on [Tue Aug 15 2017](https://github.com/datacamp/pm-learn/issues/208)

### Summary

Collaborator and package creator Martin Maechler is incorrectly named "tests Martin Maechler": https://www.rdocumentation.org/collaborators/name/tests%20Martin%20Maechler. Not sure if it should be merged with https://www.rdocumentation.org/collaborators/name/Martin%20Maechler.

Also looks strange in search results:

<img width="470" alt="martin" src="https://user-images.githubusercontent.com/10160857/29326994-9e432816-81bb-11e7-874b-075598033b95.PNG">

---

@ramnathv commented on [Tue Aug 15 2017](https://github.com/datacamp/pm-learn/issues/208#issuecomment-322533617)

@filipsch can we look into this? Martin Maechler is an R Core member, and so the sooner we can fix this the better.

**Comment by jhoobergs** [comment]
"tests Martin Maechler" isn't the only incorrect namings.
The (dev) database contains these collaborators with different email:

![image](https://user-images.githubusercontent.com/10081260/29354851-086b454e-826f-11e7-8368-6e0cdb9a114b.png)

There are even 2 records of a collaborator called Martin Maechler, which means that https://www.rdocumentation.org/collaborators/name/Martin%20Maechler only gives info about one of the 2 records.

**Comment by sabrinamoin** [comment]
From Martin today:

> Thank you, Sabrina, but it is not fixed yet... 
> 
> What I (now only?) see is that I exist twice, once as 'Martin Maechler', once as 'tests Martin Maechler'.... and my numerous packages are "evenly" distributed to one or the other of my aliases. 
> 
> So to fix your problem, you have to carefully *merge* my two aliases into 'Martin Maechler' i.e. move all the packages now attributed to 'tests Martin Maechler' over to 'Martin Maechler' without removing the packages that are already there...


Please advise on how to respond.

**Comment by filipsch** [comment]
cc @jhoobergs @ludov04

**Comment by ludov04** [comment]
I merged all the authors containing Martin Maechler manually in the database.

So https://www.rdocumentation.org/collaborators/name/Martin%20Maechler should now contains all contributions. 
Please get back to me if it's not the case.

More generally, authors name often contains strings that are difficult to distinguish from name, there is currently a list of strings often used to filter that out. (https://github.com/datacamp/RDocumentation-app/blob/master/api/services/AuthorService.js#L130)
I'm making an issue to enhance that list. That list originally came from depsy source code, see https://github.com/Impactstory/depsy/blob/59a62d6c5fda09f5d390be2b81bc886e79ba63f1/models/byline.py#L21
