### ISSUE TITLE
Report logging

### ISSUE THREAD

**Issue by ludov04** [datacamp/RDocumentation-app#382]
Currently, RDocs-app output logs but it's not reported to any service, which makes it very difficult to debug in case of problems. 
Logs follow the `short` scheme of [morgan](https://github.com/expressjs/morgan)

@lvdh Can GCP already be used here, or should we use one of the other services (cloudwatch, papertrail, ..) ?

**Comment by lvdh** [comment]
Since it is running on AWS, integrating it with CloudWatch would probably be the fastest solution. @tothandras currently has the multiplexer (on AWS) logging to StackDriver (GCP) though. It's on ECS iirc (vs EB for RDocs) but you might be able to borrow stuff from his implementation.

**Comment by ludov04** [comment]
Logs are in cloudwatch and datadog now :)
