### ISSUE TITLE
rdocumentation.org is not showing new packages(anymore)

### ISSUE THREAD

**Issue by filipsch** [datacamp/RDocumentation-app#385]
@AndreMikulec commented on [Mon Sep 25 2017](https://github.com/datacamp/RDocumentation/issues/80)

This site is not updating packages anymore
https://www.rdocumentation.org

Today is Monday, September, 25th.

Newest packages 
glassdoor	Thu Sep 14 2017 17:53:05

---

@AndreMikulec commented on [Wed Sep 27 2017](https://github.com/datacamp/RDocumentation/issues/80#issuecomment-332643102)

Still,
Nothing has changed.

This site is not updating packages anymore
https://www.rdocumentation.org
is still stuck at
"
Today is Monday, September, 25th.

Newest packages
glassdoor	Thu Sep 14 2017 17:53:05
"

---

@filipsch commented on [Thu Sep 28 2017](https://github.com/datacamp/RDocumentation/issues/80#issuecomment-332739555)

@AndreMikulec thanks for flagging this; we'll look into it as soon as we have some bandwidth.

---

@filipsch commented on [Thu Sep 28 2017](https://github.com/datacamp/RDocumentation/issues/80#issuecomment-332739950)

Moving this issue to the rdocumentation-app repo, as that repo hosts the code for the node app that serves rdocumentation.org.

**Comment by ludov04** [comment]
Working again now
