### ISSUE TITLE
rdocumentation.org is not showing new packages(anymore) yet again.

### ISSUE THREAD

**Issue by AndreMikulec** [datacamp/RDocumentation-app#387]
This site is not updating packages anymore
https://www.rdocumentation.org

Today is Saturday, October 14th.

Newest packages 
SparkR	Thu Oct 12 2017 14:13:03

**Comment by ludov04** [comment]
Looks ok for me, beware that newest package only list packages that were not published before (excluding updates). The column on the right (newest updates) shows the updates.
It's possible that they were no new packages during 2 days
