### ISSUE TITLE
"Session disconnected" message during interactive R examples

### ISSUE THREAD

**Issue by gabrieldes** [datacamp/RDocumentation-app#391]
I wasn't able to reproduce this but users on Twitter mentioned this issue. Here's the tweet: https://twitter.com/klmr/status/932587101014589440

>Do the interactive #rstats examples on DataCamp’s rdocumentation.​org actually work for anybody? I always get “Session disconnected”.

**Comment by filipsch** [comment]
@gabrieldes it's hard to look if people don't provide a reproducible example. Closing until that happens. Thanks.
