### ISSUE TITLE
rdocumentation.org Newest Packages has stopped again - stopped at Dec 23 2017

### ISSUE THREAD

**Issue by AndreMikulec** [datacamp/RDocumentation-app#394]
Today is Thursday, January 4th, 2018 at 12:16 p.m. Central Time.

The page is still the same.

https://www.rdocumentation.org/trends
```
Newest packages 
```
```
CytobankBridgeR Sat Dec 23 2017 21:54:39
hydroscoper     Fri Dec 22 2017 18:52:37
pKSEA           Fri Dec 22 2017 18:46:08
spectacles      Fri Dec 22 2017 18:33:10
```

**Comment by filipsch** [comment]
Hi @AndreMikulec we'll look into it as soon as we have the bandwidth. Thanks for flagging this!

**Comment by ludov04** [comment]
We migrated the workers to a brand new architecture. This should be way more stable now, thanks for reporting this so many times!
