### ISSUE TITLE
Cut the cruft in integration with RDocumentation R package

### ISSUE THREAD

**Issue by filipsch** [datacamp/RDocumentation-app#395]
The RDocumentation R package, when loaded in RStudio, integrates seamlessly with the RDocumentation.org website: help functions are overridden, and the help page shows in the RStudio viewer pane when doing, e.g. `?mean`. However, there are many links between the two, that are overly complicated, hacky, buggy and we don't even know if they are helpful to our users.

This is the list:
- When you open up a help page, the RDocumentation.org checks the version of the package you're running, and prompts you to update your package (it expects to a hard-coded, outdated version of RDocumentation). If you accept, it will execute R code to update RDocumentation to the latest version. If you click it, the R session simply crashes.
- When you open up a help page, you have the ability to run the examples of the help page immediately inside your running session. However, if the package that the function belongs to does not exist, or if the local package version does not match the package version listed on the help page, clicking "Run Example" will do nothing. If the package is installed and the version matches, the R session crashes.
- If a package is not installed, there is code (not sure if it is available to the user still) that allows you to install the package on the fly. This is pretty cool, but the function is pretty buggy as well.
- There is the ability to log in into RDocumentation.org from inside RStudio, storing your credentials to your local machine, auto-logging you in next time. This is insecure, and buggy as well.
- The menu bar does not show up; we should simply not show it.

We currently don't have the bandwidth to double down on a crazy integrations between an R package and a dynamically loaded RDocumentation page that is served inside RStudio. Until then, we should reduce functionality and make the functionality we keep as robust as possible. Cut the cruft, basically, and see what features people ask for, and build them up again. I suggest:

- [x] Remove _any_ interaction that happens between RDocs and RStudio, for checking package version, installing new versions, setting RDocs as the default, or executing examples.
- [x] Disable the ability to log in through parameters in the URL.
- [x] Update the UI of the help pages to remove any components that depend on this interaction.
- [x] Fix the navbar.

**Comment by ludov04** [comment]
Cleaned up all the interactions, fixed the navbar, removed lot of code.
The package is working again :) !
