### ISSUE TITLE
Write article that explains how to restart the package parsing

### ISSUE THREAD

**Issue by filipsch** [datacamp/RDocumentation-app#399]
Sometimes, package parsing goes wrong. Typically, people raise an issue about the package docs on RDocs not being updated to the latest version. The way to fix it is easy, by retriggering the job on AWS, but it is not clear how to do this.

- [ ] Write section in the GitHub wiki.
- [ ] Use the approach to retrigger the parsing, which hopefully fixes #386 and #392 

There is currently no bandwidth to solve this issue at the core, so we'll have to go with this 'Have you tried restarting' approach until there is more time.

**Comment by ludov04** [comment]
I think #392 is a completely different issue that will need more investigation

**Comment by ludov04** [comment]
@filipsch I think you are mixing 2 issues here. 

- One issue is that sometime, the parsing goes wrong for one package, like the surveillance one, this is the case when the r-package-parse choke on the package for some reason, when it occurs, it just send the message to the dead-letter sqs queue and continue the normal work.

- Second issue is that, sometime the parsing stop completely for an unknown reason, the fix in this case is to restart the r-package-parser worker that is on ECS and the rdocumentation-app workers that are on ElasticBeanstalk

 #386 is part of the first issue, which mean `r-package-parser` is unable to process it for some reason, and that cannot be fixed just by restarting

**Comment by filipsch** [comment]
@ludov04 okay I see. I would not look into detail into #386. Not sure why I mentioned #392; it's not relevant here. It should have been #394.

**Comment by ludov04** [comment]
Rdoc-R-Worker is now on the new cluster, so it have all the ecs-deploy toolbox including restart, overall it should be more stable and we also get logs
