### ISSUE TITLE
Write OSS-worthy README

### ISSUE THREAD

**Issue by filipsch** [datacamp/RDocumentation-app#400]
Currently, the readme is very much focussed on all the features, which is very interesting. In addition, however, the README should contain:

- [x] What the app does (be concise).
- [x] Where to find different pieces of documentation.
- [x] Instructions on how to run (and how to assess the app works). (Double check if these instructions actually do the trick).
- [x] Instructions on how to deploy, and where the deploy is hosted.
- [x] Description of the steps the CI does.
- [ ] Guidelines to contribute.

**Comment by ludov04** [comment]
Updated the readme
