### ISSUE TITLE
Fix stability issues related to ElasticSearch

### ISSUE THREAD

**Issue by filipsch** [datacamp/RDocumentation-app#401]
From time to time, ElasticSearch goes down because ramp-up of CPU. @ludov04 suggested to solve this to move this indexing service to an ECS task instead of running as a background process. Estimated to be 3h of work.

- [ ] Move functionality to ECS task
- [ ] Write wiki article about how the indexing is working, how to restart and how to troubleshoot.

**Comment by ludov04** [comment]
Elasticsearch is now managed by aws, no more restarting or heart-attack
