### ISSUE TITLE
rdocumentation.org Newest Packages has stopped again - stopped Mon Jan 29 2018

### ISSUE THREAD

**Issue by AndreMikulec** [datacamp/RDocumentation-app#403]
rdocumentation.org Newest Packages has stopped again

https://www.rdocumentation.org/trends

Today is Sat Feb 03 2018

```r
Newest packages 

dirichletprocess     Mon Jan 29 2018 18:23:55
ROlogit              Mon Jan 29 2018 18:11:51
dalmatian            Mon Jan 29 2018 12:44:05
```

**Comment by AndreMikulec** [comment]
rdocumentation.org Newest Packages is still stopped.
( https://www.rdocumentation.org/trends )

Today is Thu Feb 15.

```r
Newest packages 

dirichletprocess   Mon Jan 29 2018 18:23:55
ROlogit            Mon Jan 29 2018 18:11:51
dalmatian          Mon Jan 29 2018 12:44:05

```

**Comment by AndreMikulec** [comment]
rdocumentation.org Newest Packages is still stopped.
( https://www.rdocumentation.org/trends )

Today is Mon Mar 12.
```r
Newest packages 

SourceSet    Wed Feb 28 2018 17:36:07
tailr        Wed Feb 28 2018 17:07:02
SpatEntropy  Wed Feb 28 2018 16:51:14
```

**Comment by ludov04** [comment]
We migrated the workers to a brand new architecture. This should be way more stable now, thanks for reporting this so many times!
