### ISSUE TITLE
On-hover functionality broken

### ISSUE THREAD

**Issue by filipsch** [datacamp/RDocumentation-app#404]
To reproduce:

- Go to https://www.rdocumentation.org/packages/mosaic/versions/1.1.1/topics/pdist
- Hover over `xqnorm()`, for example:

https://www.dropbox.com/s/fece5gh0u0qlwvl/Screenshot%202018-03-28%2002.40.22.png?dl=0
![image](https://user-images.githubusercontent.com/5768479/38002271-7a8dfe38-3231-11e8-8373-b1c5784227b2.png)

@ludov04 I think the feature is not polished enough since Jesse worked on it; it is poorly designed, and now it is also not working. I would just revert it until we have more bandwidth to enable it again properly.

Urgency: high, it messes up user experience.

**Comment by ludov04** [comment]
Disabled it, leaving this open as the true issue is not fixed
