### ISSUE TITLE
Package updates between 2018.03.06 and 2018.03.16 are skipped

### ISSUE THREAD

**Issue by cjyetman** [datacamp/RDocumentation-app#406]
In the "Newest updates" list at https://www.rdocumentation.org/trends, there appears to be a gap between 2018.03.06 and 2018.03.16 where package updates were not recorded. Pages for individual packages that were updated during that period appear to not be updated either, e.g. sunburstR which was updated on 2018.03.12
https://www.rdocumentation.org/packages/sunburstR
https://cran.r-project.org/web/packages/sunburstR/

**Comment by ludov04** [comment]
We actually migrated infrastructure during that time period. Thanks for reporting, some packages might have been migrated incorrectly. We'll look into it

**Comment by cjyetman** [comment]
fyi... there also appears to be a gap between 2018.02.10 and 2018.02.25, e.g. countrycode which was updated on 2018.02.11
https://www.rdocumentation.org/packages/countrycode
https://cran.r-project.org/web/packages/countrycode/

**Comment by ludov04** [comment]
All packages from 2018.01.01 has been reparsed, thanks for reporting
