### ISSUE TITLE
Rendering of code chunks in vignettes

### ISSUE THREAD

**Issue by rstub** [datacamp/rdocumentation-app#421]
Looking at the [vignette of dqrng](https://www.rdocumentation.org/packages/dqrng/versions/0.0.4/vignettes/dqrng.Rmd) I see several things that are not working:

* The second code chunk gives:
    > Error: there is no package called 'dqrng'

    What's the point of making the code in a package vignette executable if the package itself is not available?
* The Second code chunk gives this additional error:
    > Error: could not find function "piR"

    That function is defined in the first code chunk. In R Markdown it is standard that such definitions are also available in subsequent code chunks. Is this possible in this interface, too.
* All the C++/Rcpp code chunks are interpreted as R code chunks. These are marked as ` {r, eval=FALSE, engine='Rcpp'}` in the Rmd, which works for the normal vignette rendering. Could these be correctly interpreted as C++/Rcpp here as well?

**Comment by ben-brooker** [comment]
The second code chunk does not give an error anymore. Closing this issue :)
