### ISSUE TITLE
Badge issue

### ISSUE THREAD

**Issue by aravind-j** [datacamp/rdocumentation-app#425]
The badge of published package still showing as __not published__. 

https://www.rdocumentation.org/packages/germinationmetrics/versions/0.1.0

[![Rdoc](http://www.rdocumentation.org/badges/version/germinationmetrics)](http://www.rdocumentation.org/packages/germinationmetrics)

**Comment by aravind-j** [comment]
The same is true for

https://www.rdocumentation.org/packages/augmentedRCBD/versions/0.1.0

[![Rdoc](http://www.rdocumentation.org/badges/version/augmentedRCBD)](http://www.rdocumentation.org/packages/augmentedRCBD)

**Comment by msberends** [comment]
And ours:

http://www.rdocumentation.org/packages/AMR

[![Rdoc](http://www.rdocumentation.org/badges/version/AMR)](http://www.rdocumentation.org/packages/AMR)

**Comment by msberends** [comment]
Any update?? We would like this to be fixed. Anything we can do ourselves??

**Comment by msberends** [comment]
Still nothing after all these months. Come on, DataCamp! Why build a documentation website if it's unreliable to use??
