### ISSUE TITLE
Allow voting on community examples

### ISSUE THREAD

**Issue by richierocks** [datacamp/rdocumentation-app#432]
Sorting the community example by most recent means that good submissions eventually get buried. for example, on the [`?mean`](https://www.rdocumentation.org/packages/base/topics/mean) page, there are dozens of examples that are blank, badly formatted, or don't contribute anything useful. The most informative examples are older, but hard to find amongst the spam.

**Comment by ben-brooker** [comment]
Closing this issue as the client-side of this application is now in the [Rdocumentation2.0](https://github.com/datacamp/rdocumentation-2.0) repo. :)
