### ISSUE TITLE
Printing of \itemize{} is rubbish

### ISSUE THREAD

**Issue by richierocks** [datacamp/rdocumentation-app#436]
For example, in [`sig::sig()`](https://www.rdocumentation.org/packages/sig/topics/sig) I see

![screenshot 2018-11-13 13 59 15](https://user-images.githubusercontent.com/197589/48436273-51c20280-e74c-11e8-813a-1d0256928cd5.png)

There are some spaces missing.

Here's [the source](https://bitbucket.org/richierocks/sig/src/7ef618eaa1310ac34427e184c46f253863a4101e/man/sig.Rd?at=master&fileviewer=file-view-default)

![screenshot 2018-11-13 13 59 57](https://user-images.githubusercontent.com/197589/48436334-70c09480-e74c-11e8-8da7-ee2287c75218.png)

**Comment by ben-brooker** [comment]
Closing this issue as the client-side of this application is now in the [Rdocumentation2.0](https://github.com/datacamp/rdocumentation-2.0) repo and this is fixed. :)
