### ISSUE TITLE
README is not displayed for some packages

### ISSUE THREAD

**Issue by mirca** [datacamp/RDocumentation-app#443]
I've noticed that some packages don't get their README file displayed, e.g., https://www.rdocumentation.org/packages/riskParityPortfolio/versions/0.1.2.

Could it be an issue with the package's README, even though it appears just fine on CRAN?

Thanks!

**Comment by msberends** [comment]
Your problem is this:

```
[![Rdoc](http://www.rdocumentation.org/badges/version/riskParityPortfolio)](http://www.rdocumentation.org/packages/riskParityPortfolio)
```

[![Rdoc](http://www.rdocumentation.org/badges/version/riskParityPortfolio)](http://www.rdocumentation.org/packages/riskParityPortfolio)

See #425, they are not responding.

**Comment by mirca** [comment]
@msberends Thanks!

cc @dppalomar
