### ISSUE TITLE
Weird Page layout

### ISSUE THREAD

**Issue by Wenyu1024** [datacamp/rdocumentation-app#452]
The Rdocumentation page for any random package/function has weird layout when I browse in chrome in my HP Win10 64 pc. The page has very wide blank margins on both two sides and all the content are visible only in the middle area (as shown in https://drive.google.com/open?id=1v2YZ86x1oWaDLotLsQT65tC0HQ4Gs-Na).

I tried to clear the cookies and browse history but it did not help.
The same issue is not observed with microsoft edge on the same pc, or chrome on my android phone.

Any idea what may go wrong?

**Comment by ben-brooker** [comment]
Closing this issue as the client-side of this application is now in the [Rdocumentation2.0](https://github.com/datacamp/rdocumentation-2.0) repo. :)
