### ISSUE TITLE
Search result redesign

### ISSUE THREAD

**Issue by ludov04** [datacamp/rdocumentation-app#56]
- Seperate the topics and packages into 2 columns. Use tabs for smaller window size.
- Pagination in the bottom on the 2 columns.
- Display the search query in the top bar
- Number of total results near "Packages" and "Topics"
- Display package description, author and percentile

See mockup:
![mockup](https://datacamp.mybalsamiq.com/mockups/4815075.png?key=6d7b1360880ff8a01e07af442efe8fad96f6658d)

**Comment by ludov04** [comment]
@louisdelanoeye This require adaptation of the search request to elasticsearch (we want to split package and function), this is the core functionality so don't do this alone.

However, you can do the front-end, so split the page in 2 (or tabs in small screen), you can display the same content in both part for now. Don't forget the pagination, ideally only the relevant part of the screen will be replaced when navigation trough the pages (if I click on page 2 on the package tab, only package result gets replaced)..

The scss contains the bootstrap grid system (http://getbootstrap.com/css/#grid), I advise you to use that, it's easier to make things responsive.

**Comment by louisdelanoeye** [comment]
@ludov04: I had actually already started last night. I just split up the elasticsearch if it's not ok I'll just revert it and we can have a look together. The front-end also had some progress I use the col-md as you suggest. For now I'm using links to go through the pages so the whole page gets reloaded maybe use AJAX requests instead then?

**Comment by ludov04** [comment]
@louisdelanoeye Still to be done:

- [ ] Display the search query in the top bar
- [ ] Number of total results near "Packages" and "Topics"
- [ ] Display package description, author and percentile
