### ISSUE TITLE
Incorrect rendering of /packages/rstudioapi/versions/0.4.0/topics/insertText

### ISSUE THREAD

**Issue by louisdelanoeye** [datacamp/RDocumentation-app#87]
The different divs are wrapped in &lt;code &gt; &lt;/code &gt;  tags which causes incorrect rendering of the page. Probably due to loading wrongly formatted file (perhaps unclosed tags).

**Comment by HannesBuseyne** [comment]
looks like the same issue appears for `getNodeSet`
http://staging.rdocumentation.org/packages/XML/versions/3.98-1.4/topics/getNodeSet

**Comment by louisdelanoeye** [comment]
That's indeed a related issue but easier to solve I'll do it in issue257 (Easier since examples can just always be displayed literally)

**Comment by ludov04** [comment]
Related to #289
